### ISSUE TITLE
papers for in-between books

### ISSUE THREAD

**Issue by rick** [nashdl/bookclub#13]
This came across my `GitHub Explore` email recently and it looks like a deep well of good CS-related papers for us to use to review periodically so we have a palate cleanser between books:

  https://github.com/papers-we-love/papers-we-love

Let's discuss interesting papers here...

@awebneck @vinbarnes @arafatm ...

**Comment by vinbarnes** [comment]
:+1: and :effyeah:

**Comment by arafatm** [comment]
:+1:

**Comment by arafatm** [comment]
So we've decided to pick a paper for the next bookclub. @rick @vinbarnes what's the suggestion?

**Comment by vinbarnes** [comment]
How about http://www.objectmentor.com/resources/articles/Principles_and_Patterns.pdf [pdf] ?

@arafatm you brought up SOLID so why not discuss it? We could also pick more than one paper if they supplement the topic.

**Comment by rick** [comment]
Stale like James' EE degree.
