### ISSUE TITLE
Plan for discussing "The Timeless Way of Building"

### ISSUE THREAD

**Issue by rick** [nashdl/bookclub#14]
We mentioned this in today's book club -- how do we want to approach this book?

My thoughts were doing a round of pre-processing before we get into it:
- Get a copy of the book
- Open up to basically page "vi" (unmarked), which has the header "ON READING THIS BOOK", and read that
- then hit "ix" through "xv", which is a "detailed table of contents", and read that
- then do what he says in "ON READING THIS BOOK" to basically read the book in an hour

Then come back and comment here on how you think we should further read / discuss this.

Seem reasonable?

/cc @arafatm @vinbarnes @awebneck @brandonvalentine @kamarcum ... ?

**Comment by vinbarnes** [comment]
:+1:

**Comment by arafatm** [comment]
:+1:

**Comment by vinbarnes** [comment]
Finished the preview of the book. _Let's build something!_ 

How are folks coming along? If folks are still working on the overview, should we save the _How Should We Read This Book_ discussion for the first meetup?

**Comment by arafatm** [comment]
@vinbarnes I've started reading. Unfortunately this method of reading the book is alien to me. I like to go slow and take notes.

Giving a shot though.

**Comment by rick** [comment]
I'm about halfway through in reading overview-style, mostly because I'm actually just reading the book, really.  But, I've read it a number of times before anyway.

**Comment by vinbarnes** [comment]
My target is to read through _The Quality_ and _The Gate_ sections for next Thursday.

**Comment by rick** [comment]
Next-next Thursday?  I agree, those two sections would be a good amount to
cover next time.

**Comment by vinbarnes** [comment]
Sorry. Yes. Next-next Thursday. May 8. :grin:

**Comment by vinbarnes** [comment]
Since @arafatm is otherwise occupied during the normal Boocklub time Thursday May 8 12-1p, what if we temporarily adjust to another time that day or possibly another time Friday May 9? @arafatm @rick what say y'all?

**Comment by arafatm** [comment]
Thursday is shot for me. I'm down for Friday

**Comment by rick** [comment]
yeah, I could do friday

**Comment by vinbarnes** [comment]
@rick when are you available? Oddly enough I have a lunch rendezvous with Dr Crackers at 12:30-1:30p. Could we schedule it from 2-3p maybe? Honestly I'm open whenever. I could even leave work a little early and meet with y'all to discuss over :beers: in person. Let me know.

**Comment by rick** [comment]
yeah 2-3p would work for me; I think we have company coming in Friday
evening, so probably have to pass on the beers that day.

Rick

**Comment by vinbarnes** [comment]
:cool: 

@arafatm does 2-3p work for you?

**Comment by arafatm** [comment]
​Should work for me.​

**Comment by vinbarnes** [comment]
@arafatm awesome. Can you update the meetup?

**Comment by arafatm** [comment]
Where are we meeting?

**Comment by vinbarnes** [comment]
Hangout. 2-3p on Friday.

**Comment by rick** [comment]
Stale.  Closing.
