### ISSUE TITLE
rules of engagement

### ISSUE THREAD

**Issue by vinbarnes** [nashdl/bookclub#3]
Leaving this here to gather some feedback.

For me, I say please drop video, it adds nothing and possibly causes problems. Lease common denominator, blah, blah, blah.

Other than that I thought it went well once we got into the discussion. Talking over each other didn't really seem to be a problem.

A++++++ Would hangout and discuss DDD again!

**Comment by vinbarnes** [comment]
Despite my love of **VIDEO!!!!!!**,

```
audio > video
```

for this.

**Comment by bval** [comment]
Honestly, I :heart: :video_camera: and would rather see your pretty faces. Is bandwidth really that bad at the places folks work?

**Comment by vinbarnes** [comment]
The audio garbled and noticed people dropped out more than once. I had the window in the background while I was looking at the book text anyway. Just a consideration to ensure a better experience for all. 

Also, did stratasan not join up? Don't remember them on the call.

**Comment by arafatm** [comment]
I could go either way on the video. But I have noticed a drop in audio quality with video turned on. Anyone know if it's possible to turn off video on the receiving end?

Brian @ Stratasan couldn't make it. I never heard from anyone else there requesting to join.

**Comment by bval** [comment]
@arafatm I just figured out that the video quality slider at the top of the hangout screen will let you scale back your own bandwidth usage and go all the way down to audio only if you like. With that realization I'd say we keep it a video call and those who can't spare the bandwidth and scale it back on their end.

**Comment by arafatm** [comment]
@brandonvalentine good lookin out

**Comment by arafatm** [comment]
Looks like brandon's suggestion to limit the bandwidth on your end is a good one.

**Comment by vinbarnes** [comment]
Yep, it worked out well for us. Appreciate the tip, @brandonvalentine.
