### ISSUE TITLE
outlining reading assignments

### ISSUE THREAD

**Issue by vinbarnes** [nashdl/bookclub#4]
Going forward it would be good for everyone to have an expectation of the reading assignment for each meetup.

**Comment by nessamurmur** [comment]
:+1:

**Comment by vinbarnes** [comment]
@arafatm not sure what the best approach is here but maybe for each book directory we can have a syllabus?

**Comment by arafatm** [comment]
I like the idea of 2 sessions (1 every 2 weeks) per book. So 1/2 a book every 2 weeks. Keeps it simple without having to break down each book.

**Comment by arafatm** [comment]
Didn't mean to close the issue. Just comment :/

**Comment by bval** [comment]
:thumbsup: for 2 sessions per book, and every other week.

**Comment by vinbarnes** [comment]
So did we say what exactly 1/2 the book is for this next reading assignment of The Drunkard's Walk? Sorry. If things aren't explicit and I don't write them down I am nothing but a child lost in the forest. Thanks.

_I'm assuming up through Ch. 5_

**Comment by arafatm** [comment]
@vinbarnes :+1:  Reading through Ch 5 sounds good.
