### ISSUE TITLE
When not to DDD?

### ISSUE THREAD

**Issue by kamarcum** [nashdl/bookclub#7]
The title says most of it. When will DDD probably not work?

We can, though software, make things that spoken language doesn't yet describe. Maybe that's a good indicator that DDD wouldn't work well.

As a contrived example, let's pretend Twitter was completely novel and not modeled partially after SMS. Words for Tweet and Hashtag didn't exist. Could they still use DDD effectively, but with a glossary for their made-up words?

Perhaps that's where most software ends up. Since fidelity is lost in the meatspace to software conversion, when I use the word Car as a domain term, it is neither "car" in the dictionary, nor the vehicle in the parking lot, but car the domain term in the context of this domain and software project.

Thoughts?

**Comment by arafatm** [comment]
@kamarcum Good discussion on this today. Thanks for bringing it up.

Gonna close unless you want to add anything to it?
